spring:
  profiles:
    active: local
    include: 
      - charge
    group:
      local: local-db
      dev: dev-db
  jpa:
    hibernate:
      ddl-auto: none
  batch:
    jdbc:
      initialize-schema: always

server:
  port: 8301

